version: '3.8'

services:
  backend:
    build:
      context: ./backend-core
      dockerfile: Dockerfile
      args:
        CACHEBUST: ${CACHEBUST:-1}
    container_name: starta-backend-1
    restart: always
    ports:
      - "8000:7860"
    env_file:
      - .env
    volumes:
      - ./backend-core:/app
      - /opt/starta/data:/app/data
    networks:
      - starta-network

  caddy:
    image: caddy:alpine
    container_name: starta-caddy-1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
    networks:
      - starta-network

volumes:
  caddy_data:
  caddy_config:


networks:
  starta-network:
    driver: bridge
