version: '3.8'

services:
  backend:
    build:
      context: ./backend-core
      dockerfile: Dockerfile
      args:
        CACHEBUST: ${CACHEBUST:-1}
    container_name: starta-backend-1
    restart: always
    ports:
      - "8000:7860"
    env_file:
      - backend-core/.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./backend-core:/app
      - /opt/starta/data:/app/data
    networks:
      - starta-network

networks:
  starta-network:
    driver: bridge
